In [3]:
import numpy as np
datarange = np.arange(0,20)
print("datarange --> " + str(datarange))

datarange --> [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
print("type of datarange --> " + str(type(datarange)))

type of datarange --> <class 'numpy.ndarray'>


In [7]:
##----creating an matrix / 2-dimensional array from datarange
#matrix1 = np.reshape(datarange,(4,4)) ##--> it will throw an error --> ValueError: cannot reshape array of size 20 into shape (4,4)
matrix1 = np.reshape(datarange,(5,4)) ##--> By default it will populate the data row-wise/horizontally in the new 2-dimensional array / matrix
print("matrix1 --> ")
print(str(matrix1))

matrix1 --> 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [20]:
matrix2 = np.reshape(datarange,(4,5),order='C') ##--> if you use order='C', that means the data will be arranged row-wise/horizontally in the new 2-dimensional array / matrix
print("matrix2 --> ")
print(str(matrix2))

matrix2 --> 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [10]:
matrix3 = np.reshape(datarange,(4,5),order='F') ##--> if you use order='F', that means data will be arranged column-wise/vertically in the new 2-dimensional array / matrix
print("matrix3 --> ")
print(str(matrix3))

matrix3 --> 
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


In [27]:
##----printing matrix1
print("matrix1 --> ")
print(str(matrix1))
print(" ")

##----want to find out the value 10 in matrix1
print("matrix1[2,2] --> " + str(matrix1[2,2]))
print(" ")

##----want to find out the value 10 in matrix1
print("matrix1[2][2] --> " + str(matrix1[2][2]))
print(" ")

##----want to find out the index of value 10 in matrix1
item_10_loc = np.where(matrix1==10)
print("item_10_loc --> " + str(item_10_loc))
print(" ")

matrix1 --> 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
 
matrix1[2,2] --> 10
 
matrix1[2][2] --> 10
 
item_10_loc --> (array([2], dtype=int64), array([2], dtype=int64))
 


In [30]:
##----printing matrix2
print("matrix2 --> ")
print(str(matrix2))
print(" ")

##----want to find out the value 19 in matrix2
item_19_loc = np.where(matrix2 == 19)
print ("item_19_loc --> " + str(item_19_loc))
print(" ")

##----want to find out the value 19 in matrix2
print("matrix2[3,4] --> " + str(matrix2[3,4]))
print(" ")

matrix2 --> 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
 
item_19_loc --> (array([3], dtype=int64), array([4], dtype=int64))
 
matrix2[3,4] --> 19
 


In [32]:
##----printing matrix3
print("matrix3 --> ")
print(str(matrix3))
print(" ")

##----want to find out the value 16 in matrix3
item_16_loc = np.where(matrix3 == 16)
print ("item_16_loc --> " + str(item_16_loc))
print(" ")

##----want to find out the value 16 in matrix3
print("matrix3[0,4] --> " + str(matrix3[0,4]))
print(" ")

##----want to find out the value 16 in matrix3
print("matrix3[0][4] --> " + str(matrix3[0][4]))
print(" ")

matrix3 --> 
[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
 
item_16_loc --> (array([0], dtype=int64), array([4], dtype=int64))
 
matrix3[0,4] --> 16
 
matrix3[0][4] --> 16
 


In [35]:
##----OOP concept
##--we can directly call reshape function on datarange array
print("datarange --> ")
print(str(datarange))
print(" ")

print("type(datarange) --> " + str(type(datarange)))
print(" ")

print("datarange.reshape((5,4)) --> ")
print(str(datarange.reshape((5,4))))

datarange --> 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 
type(datarange) --> <class 'numpy.ndarray'>
 
datarange.reshape((5,4)) --> 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [41]:
##----declaring three lists
l1 = ['what','am','I']
l2 = ['You','are','future']
l3 = ['my','birth','date']
l4 = [23,6,2080]

print("l1 --> " + str(l1))
print(" ")

print("l2 --> " + str(l2))
print(" ")

print("l3 --> " + str(l3))
print(" ")

print("l4 --> " + str(l4))
print(" ")

mar = np.array([l1,l2,l3,l4])

print("mar --> ") 
print(str(mar))
print(" ")

print("All the data has been converted to character data in mar 2-dimensional arry / matrix")

l1 --> ['what', 'am', 'I']
 
l2 --> ['You', 'are', 'future']
 
l3 --> ['my', 'birth', 'date']
 
l4 --> [23, 6, 2080]
 
mar --> 
[['what' 'am' 'I']
 ['You' 'are' 'future']
 ['my' 'birth' 'date']
 ['23' '6' '2080']]
 
All the data has been converted to character data in mar 2-dimensional arry / matrix
