In [2]:
##----importing python package --> numpy
##----importing python package --> InteractiveShell
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

arr1 = np.array([[100,101,102,103,104,105,106,107,108,109],[200,201,202,203,204,205,206,207,208,209]])

print("==========================================================")
print("                                                          ")
print(" Array arr1 --> ")
print(arr1)
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("Type of arr1 --> " + str(type(arr1)))
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("Sum of all vaules in arr1 --> " + str(arr1.sum()))
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("Minimum value in arr1 --> " + str(arr1.min()))
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("Maximum value in arr1 --> " + str(arr1.max()))
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("Size of arr1 --> " + str(arr1.size))
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("Shape of arr1 --> " + str(arr1.shape))
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("Memory location of arr1 --> " + str(arr1.data))
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("Datatype of arr1 --> " + str(arr1.dtype))
print("                                                          ")
print("==========================================================")
print("                                                          ")

                                                          
 Array arr1 --> 
[[100 101 102 103 104 105 106 107 108 109]
 [200 201 202 203 204 205 206 207 208 209]]
                                                          
                                                          
Type of arr1 --> <class 'numpy.ndarray'>
                                                          
                                                          
Sum of all vaules in arr1 --> 3090
                                                          
                                                          
Minimum value in arr1 --> 100
                                                          
                                                          
Maximum value in arr1 --> 209
                                                          
                                                          
Size of arr1 --> 20
                                                          
                                

In [39]:
rows,columns = arr1.shape
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("No of rows in arr1 --> " + str(rows))
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("No of columns in arr1 --> " + str(columns))
print("                                                          ")
print("==========================================================")
print("                                                          ")

                                                          
                                                          
No of rows in arr1 --> 2
                                                          
                                                          
No of columns in arr1 --> 10
                                                          
                                                          


In [40]:
##----printing all the elements in arr1
for i in range(0,rows):
    for j in range(0,columns):
        print("Value of arr1[" + str(i) + "][" + str(j) + "] --> " + str(arr1[i][j]))

Value of arr1[0][0] --> 100
Value of arr1[0][1] --> 101
Value of arr1[0][2] --> 102
Value of arr1[0][3] --> 103
Value of arr1[0][4] --> 104
Value of arr1[0][5] --> 105
Value of arr1[0][6] --> 106
Value of arr1[0][7] --> 107
Value of arr1[0][8] --> 108
Value of arr1[0][9] --> 109
Value of arr1[1][0] --> 200
Value of arr1[1][1] --> 201
Value of arr1[1][2] --> 202
Value of arr1[1][3] --> 203
Value of arr1[1][4] --> 204
Value of arr1[1][5] --> 205
Value of arr1[1][6] --> 206
Value of arr1[1][7] --> 207
Value of arr1[1][8] --> 208
Value of arr1[1][9] --> 209


In [41]:
##----printing all the elements in arr1
for i in range(0,rows):
    for j in range(0,columns):
        print("Value of arr1[" + str(i) + "," + str(j) + "] --> " + str(arr1[i,j]))

Value of arr1[0,0] --> 100
Value of arr1[0,1] --> 101
Value of arr1[0,2] --> 102
Value of arr1[0,3] --> 103
Value of arr1[0,4] --> 104
Value of arr1[0,5] --> 105
Value of arr1[0,6] --> 106
Value of arr1[0,7] --> 107
Value of arr1[0,8] --> 108
Value of arr1[0,9] --> 109
Value of arr1[1,0] --> 200
Value of arr1[1,1] --> 201
Value of arr1[1,2] --> 202
Value of arr1[1,3] --> 203
Value of arr1[1,4] --> 204
Value of arr1[1,5] --> 205
Value of arr1[1,6] --> 206
Value of arr1[1,7] --> 207
Value of arr1[1,8] --> 208
Value of arr1[1,9] --> 209


In [54]:
##----creating view on arr1
arr2 = np.array([arr1[1,8],arr1[1,9]])

print("arr2 --> " + str(arr2))
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("Type of arr2 --> " + str(type(arr2)))

arr2 --> [208 209]
                                                          
                                                          
Type of arr2 --> <class 'numpy.ndarray'>


In [63]:
##----updating arr2
arr2[1] = 215

print("==========================================================")
print("                                                          ")
print("arr2 --> " + str(arr2))
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("arr1 --> " + str(arr1))
print("                                                          ")
print("==========================================================")
print("                                                          ")  
print("No change in arr1")
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("So the view is not created")
print("                                                          ")
print("==========================================================")

                                                          
arr2 --> [208 215]
                                                          
                                                          
arr1 --> [[100 101 102 103 104 105 106 107 108 109]
 [200 201 202 203 204 205 206 207 208 209]]
                                                          
                                                          
No change in arr1
                                                          
                                                          
So the view is not created
                                                          


In [32]:
##----trying to create view on arr1 by slicing data data from it
arr3 = arr1[:][:]
print("==========================================================")
print("                                                          ")
print("arr3 --> ")
print(arr3)
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("Modifying value of arr3[1,9] from 209 to 309")
arr3[1,9] = 309
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("Now arr3 --> ")
print(arr3)
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("Value of arr1[1,9] is also modified now --> ")
print(arr1)
print("                                                          ")
print("==========================================================")
print("                                                          ")
print("Creating another array arr4 from arr1 by slicing data from it arr1[1][8:10]")
print("                                                          ")
arr4 = arr1[1][9:10]
print("arr4 --> " + str(arr4))
print("                                                          ")
print("Type of arr4 --> " + str(type(arr4)))
print("                                                          ")
print("Modifying value of arr4 fro 309 to 209 --> arr4[0] = 209")
print("                                                          ")
arr4[0] = 209
print("New value of arr4 --> " + str(arr4))
print("                                                          ")
print("New value of arr1 --> ")
print(arr1)
print("                                                          ")
print("==========================================================")

                                                          
arr3 --> 
[[100 101 102 103 104 105 106 107 108 109]
 [200 201 202 203 204 205 206 207 208 209]]
                                                          
                                                          
Modifying value of arr3[1,9] from 209 to 309
                                                          
                                                          
Now arr3 --> 
[[100 101 102 103 104 105 106 107 108 109]
 [200 201 202 203 204 205 206 207 208 309]]
                                                          
                                                          
Value of arr1[1,9] is also modified now --> 
[[100 101 102 103 104 105 106 107 108 109]
 [200 201 202 203 204 205 206 207 208 309]]
                                                          
                                                          
Creating another array arr4 from arr1 by slicing data from it arr1[1][8:10]
                  